### ISSUE TITLE
Link to generated PDF

### ISSUE THREAD

**Issue by srid** [BartoszMilewski/DaoFP#1]
It would be useful to the onlookers to add a link to the PDF somewhere, maybe on the GitHub repo sidebar to the right.

https://github.com/BartoszMilewski/Publications/blob/master/TheDaoOfFP/DaoFP.pdf

**Comment by BartoszMilewski** [comment]
Done!

**Comment by srid** [comment]
Nice work, btw. Chapter 1 is already interesting. Gives me a new perspective ... I'll finish it.
