### ISSUE TITLE
Typo? Closing parenthesis instead of a bracket.

### ISSUE THREAD

**Issue by vojkog** [BartoszMilewski/DaoFP#12]
(D, \Delta_x] 

https://github.com/BartoszMilewski/DaoFP/blob/c84bf5ed0fa45c5f29ab38aacb32797ba8cac63b/9-NaturalTransformations.tex#L681

**Comment by BartoszMilewski** [comment]
Thanks, fixed.

**Comment by BartoszMilewski** [comment]
Done
