### ISSUE TITLE
Maybe a bit more clear wording around not having internal elements

### ISSUE THREAD

**Issue by igr** [BartoszMilewski/DaoFP#20]
In 1.3 you are talking about the global elements of an object, its structure ("An object has no parts but it may have structure."). For a moment I was puzzled by this line:

https://github.com/BartoszMilewski/DaoFP/blob/eb75b8d70a4421f3ec8e2dcaafc7e4ab1ae356b4/2-Composition.tex#L72

until I shortly realized there are no _internal_ elements in the object. Maybe it makes sense to emphasize that internal elements do not exist in 1.3 as well; or just remind us here that the public structure exists?

Sorry If I missed something, for me this was a small glitch in understanding.

**Comment by BartoszMilewski** [comment]
I often have the urge to rephrase a sentence for emphasis, but I'm afraid to dilute the meaning. No internal structure means just that: There are no parts inside, so what else can I add?
