### ISSUE TITLE
Suggested answers to exercises

### ISSUE THREAD

**Issue by lawrence-koh** [BartoszMilewski/DaoFP#5]
I find the exercises helpful as they help readers to reinforce and deepen their understanding of the topic.

Would it be possible to provide answers to the exercises, so that we could compare with our own answers and ensure that our understanding of a concept is correct?

**Comment by BartoszMilewski** [comment]
I might do that after I'm done editing

**Comment by lawrence-koh** [comment]
got it thank you!
